### ISSUE TITLE
Documentation does not exist

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-itext#6]
Hi, I notice that this extension was released with metadata that pointed to https://quarkiverse.github.io/quarkiverse-docs/itext/dev/, but that page doesn't exist. I don't know if the right fix is to create docs or adjust the metadata.

**Comment by melloware** [comment]
Thanks for reporting I had the wrong URL in the extension!

**Comment by melloware** [comment]
3.0.2 is released it should look better now
